# Generated by Django 6.0.6 on 2026-07-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ja', 'Japanese')], default='en', help_text='Preferred language for the user interface and emails.', max_length=10, verbose_name='language'),
        ),
    ]
