# Generated by Django 6.0.6 on 2026-07-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_language_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('sepia', 'Sepia')], default='light', help_text='Preferred colour theme for the user interface.', max_length=10, verbose_name='theme'),
        ),
    ]
