# Generated by Django 6.0.6 on 2026-07-05 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WireguardInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Interface name, e.g. wg0', max_length=15, unique=True)),
                ('listen_port', models.PositiveIntegerField(default=51820)),
                ('subnet', models.CharField(help_text='Subnet for peer IP allocation, e.g. 10.0.0.0/24', max_length=43)),
                ('server_public_key', models.CharField(blank=True, max_length=44)),
                ('server_endpoint_host', models.CharField(help_text='Public IP or hostname clients use to reach this server', max_length=253)),
                ('conf_file_path', models.CharField(help_text='Absolute path to the .conf file, e.g. /etc/wireguard/wg0.conf', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WireGuard interface',
                'verbose_name_plural': 'WireGuard interfaces',
            },
        ),
        migrations.CreateModel(
            name='PeerConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for this client device', max_length=100)),
                ('peer_public_key', models.CharField(help_text='WireGuard public key for this peer', max_length=44, unique=True)),
                ('allowed_ips', models.CharField(help_text='IP/CIDR assigned to this peer, e.g. 10.0.0.2/32', max_length=43)),
                ('dns', models.CharField(blank=True, default='1.1.1.1,1.0.0.1', help_text='Comma-separated DNS servers for the client config', max_length=255)),
                ('setup_acknowledged', models.BooleanField(default=False, help_text='User has confirmed they saved the private key / QR code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_configs', to=settings.AUTH_USER_MODEL)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='wireguard.wireguardinterface')),
            ],
            options={
                'verbose_name': 'peer configuration',
                'verbose_name_plural': 'peer configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInterfaceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_access', to=settings.AUTH_USER_MODEL)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='wireguard.wireguardinterface')),
            ],
            options={
                'verbose_name': 'user interface access',
                'verbose_name_plural': 'user interface accesses',
                'unique_together': {('user', 'interface')},
            },
        ),
    ]
